name: Deploy to AWS
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /var/www/younique
            git pull origin main
            echo "export const auth = null; export default null;" > e-commerce/src/firebase.js
            sed -i 's|localhost:8000|54.66.53.33|g' e-commerce/src/utils/imageHelper.js
            cd /var/www/younique/e-commerce
            npm install
            npm run build
            cd /var/www/younique/backend
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx